apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wqwjfamju-go 
  janus-idp.io/tekton: wqwjfamju-go
  backstage.io/kubernetes-id: wqwjfamju-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wqwjfamju-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml